### ISSUE TITLE
Possible irregularities when 2+ people are typing on the same line?

### ISSUE THREAD

**Issue by knowtheory** [OpenNews/etherpad-lite#2]
I noticed in today's OpenNews call that there was a little weirdness.

Ben Welsh was writing an explanation of something, and filling out a paragraph's worth of text.  I was simultaneously trying to fix a typo on the line (and there might have been a third person trying to do something as well).  For some reason, the text Ben had typed in duplicated, so the line was a bit of a jumble.

I think @kissane may have done the line cleanup (and so maybe was one of the people editing?) but i am not certain, and i'm not entirely certain how to replicate the behavior.  Maybe just get some folks into a pad and smash on it for a bit.

Just wanted to flag it so we had a record of this.

**Comment by kissane** [comment]
Innnnteresting. I pasted in a URL from my browser's address bar into the middle of Ben's text, and suddenly there was that weird dupe, so there were def three of us working in the same small area.

**Comment by ryanpitts** [comment]
closing this after updating etherpad-lite to v1.7.0 https://github.com/OpenNews/etherpad-lite/commit/36d85472e5fb71c982164f87343cabdb55445253
